// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4cL1V-OcsDV5X4ogiYQdxc-srffUddC4',
    appId: '1:1018990527501:web:76a0b28054abd4194cc144',
    messagingSenderId: '1018990527501',
    projectId: 'mytodoapp-af0c2',
    authDomain: 'mytodoapp-af0c2.firebaseapp.com',
    storageBucket: 'mytodoapp-af0c2.appspot.com',
    measurementId: 'G-4X1R7HMBSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpLHBQDlfJwbgt-Zvs25w0EEyZ27TulA8',
    appId: '1:1018990527501:android:1fb7287f1b7d4fe64cc144',
    messagingSenderId: '1018990527501',
    projectId: 'mytodoapp-af0c2',
    storageBucket: 'mytodoapp-af0c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7JMd-Axp0pWiXB0nMalpfBRGikI2tu8Q',
    appId: '1:1018990527501:ios:e7fe7cfd7373e2cb4cc144',
    messagingSenderId: '1018990527501',
    projectId: 'mytodoapp-af0c2',
    storageBucket: 'mytodoapp-af0c2.appspot.com',
    iosClientId: '1018990527501-kghcnou6kmiv1ge5etjkgqgmnhcjm0tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7JMd-Axp0pWiXB0nMalpfBRGikI2tu8Q',
    appId: '1:1018990527501:ios:e7fe7cfd7373e2cb4cc144',
    messagingSenderId: '1018990527501',
    projectId: 'mytodoapp-af0c2',
    storageBucket: 'mytodoapp-af0c2.appspot.com',
    iosClientId: '1018990527501-kghcnou6kmiv1ge5etjkgqgmnhcjm0tb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
